sh_binary(
    name = "rename_sh",
    srcs = ["rename.sh"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "flash_sh",
    srcs = ["flash.sh"],
    visibility = ["//visibility:public"],
)
