# load("//deployment/bazel:srp_component.bzl", "srp_component")

# srp_component(
#     name = "temp_service",
#     bin = "//mw/temp/service:temp_service_mw",
#     configs = [
#         ":config",
#     ],
#     add_configs = [
#         "config.json",
#     ],
#     visibility = ["//deployment/cpu:__subpackages__"],
# )
# filegroup(
#     name = "config",
#     srcs = ["app.json"],
#     visibility = ["//deployment/mw:__subpackages__"],
# )
