py_binary(
    name = "generator",
    srcs = ["generator.py"],
    deps=["//deployment/tools/configs/local_app_generator/lib"],
    visibility = ["//visibility:public"],
    imports = ["."]
)


py_binary(
    name = "app_generator",
    srcs = ["app_generator.py"],
    deps=["//deployment/tools/configs/local_app_generator/lib"],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "app_diag_gen",
    srcs = ["app_diag_gen.py"],
    deps=["//deployment/tools/configs/local_app_generator/lib"],
    visibility = ["//visibility:public"],
)


py_binary(
    name = "cpu_gen",
    srcs = ["cpu_gen.py"],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "someip_code_generator",
    srcs = ["someip_code_generator.py"],
    visibility = ["//visibility:public"],
)