filegroup(
    name = "read_vin_job",
    srcs = [
        "read_vin.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "start_rid",
    srcs = [
        "start_rid.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "hard_restart",
    srcs = [
        "hard_restart.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "dtc_jobs",
    srcs = [
        "dtc_list.json",
        "dtc_list_by_mask.json",
        "dtc_snapshot.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)
