filegroup(
    name = "MW_APPs",
    srcs = [
        "//deployment/mw/diag/dtc:config",
        "//deployment/mw/em:config",
        "//deployment/mw/tempService:app_config"
    ],
    visibility = ["//deployment:__subpackages__"],
)
