filegroup(
    name = "Apps",
    srcs = [
        "//deployment/apps/diag_ota/ec:app_config",
        "//deployment/apps/diag_ota/fc:app_config",
        "//deployment/apps/engine_app:app_config",
        "//deployment/apps/env_service:app_config",
        "//deployment/apps/example:app_config",
        "//deployment/apps/logger_service:app_config",
        "//deployment/apps/prim_service:app_config",
        "//deployment/apps/servo_service:app_config",
        "//deployment/apps/example2/example:app_config",
        "//deployment/apps/exampleApp:app_config",
    ],
    visibility = ["//deployment:__subpackages__"],
)
